from collections import namedtuple
from ._wrapper import RIGHTS, new_cap_rights, cap_rights_init


class Right(namedtuple('Right', 'name value')):
    ALL = set()

    def __new__(cls, *args, **kwargs):
        ret = super(Right, cls).__new__(cls, *args, **kwargs)
        cls.ALL.add(ret)
        return ret

    def __int__(self):
        return self.value

    def __iter__(self):
        raise NotImplementedError


CAP_ACCEPT = Right("CAP_ACCEPT", RIGHTS['CAP_ACCEPT'])
CAP_ACL_CHECK = Right('CAP_ACL_CHECK', RIGHTS['CAP_ACL_CHECK'])
CAP_ACL_DELETE = Right('CAP_ACL_DELETE', RIGHTS['CAP_ACL_DELETE'])
CAP_ACL_GET = Right('CAP_ACL_GET', RIGHTS['CAP_ACL_GET'])
CAP_ACL_SET = Right('CAP_ACL_SET', RIGHTS['CAP_ACL_SET'])
CAP_BIND = Right('CAP_BIND', RIGHTS['CAP_BIND'])
CAP_BINDAT = Right('CAP_BINDAT', RIGHTS['CAP_BINDAT'])
CAP_CHFLAGSAT = Right('CAP_CHFLAGSAT', RIGHTS['CAP_CHFLAGSAT'])
CAP_CONNECT = Right('CAP_CONNECT', RIGHTS['CAP_CONNECT'])
CAP_CONNECTAT = Right('CAP_CONNECTAT', RIGHTS['CAP_CONNECTAT'])
CAP_CREATE = Right('CAP_CREATE', RIGHTS['CAP_CREATE'])
CAP_EVENT = Right('CAP_EVENT', RIGHTS['CAP_EVENT'])
CAP_EXTATTR_DELETE = Right('CAP_EXTATTR_DELETE', RIGHTS['CAP_EXTATTR_DELETE'])
CAP_EXTATTR_GET = Right('CAP_EXTATTR_GET', RIGHTS['CAP_EXTATTR_GET'])
CAP_EXTATTR_LIST = Right('CAP_EXTATTR_LIST', RIGHTS['CAP_EXTATTR_LIST'])
CAP_EXTATTR_SET = Right('CAP_EXTATTR_SET', RIGHTS['CAP_EXTATTR_SET'])
CAP_FCHDIR = Right('CAP_FCHDIR', RIGHTS['CAP_FCHDIR'])
CAP_FCHFLAGS = Right('CAP_FCHFLAGS', RIGHTS['CAP_FCHFLAGS'])
CAP_FCHMOD = Right('CAP_FCHMOD', RIGHTS['CAP_FCHMOD'])
CAP_FCHMODAT = Right('CAP_FCHMODAT', RIGHTS['CAP_FCHMODAT'])
CAP_FCHOWN = Right('CAP_FCHOWN', RIGHTS['CAP_FCHOWN'])
CAP_FCHOWNAT = Right('CAP_FCHOWNAT', RIGHTS['CAP_FCHOWNAT'])
CAP_FCNTL = Right('CAP_FCNTL', RIGHTS['CAP_FCNTL'])
CAP_FEXECVE = Right('CAP_FEXECVE', RIGHTS['CAP_FEXECVE'])
CAP_FLOCK = Right('CAP_FLOCK', RIGHTS['CAP_FLOCK'])
CAP_FPATHCONF = Right('CAP_FPATHCONF', RIGHTS['CAP_FPATHCONF'])
CAP_FSCK = Right('CAP_FSCK', RIGHTS['CAP_FSCK'])
CAP_FSTAT = Right('CAP_FSTAT', RIGHTS['CAP_FSTAT'])
CAP_FSTATAT = Right('CAP_FSTATAT', RIGHTS['CAP_FSTATAT'])
CAP_FSTATFS = Right('CAP_FSTATFS', RIGHTS['CAP_FSTATFS'])
CAP_FSYNC = Right('CAP_FSYNC', RIGHTS['CAP_FSYNC'])
CAP_FTRUNCATE = Right('CAP_FTRUNCATE', RIGHTS['CAP_FTRUNCATE'])
CAP_FUTIMES = Right('CAP_FUTIMES', RIGHTS['CAP_FUTIMES'])
CAP_FUTIMESAT = Right('CAP_FUTIMESAT', RIGHTS['CAP_FUTIMESAT'])
CAP_GETPEERNAME = Right('CAP_GETPEERNAME', RIGHTS['CAP_GETPEERNAME'])
CAP_GETSOCKNAME = Right('CAP_GETSOCKNAME', RIGHTS['CAP_GETSOCKNAME'])
CAP_GETSOCKOPT = Right('CAP_GETSOCKOPT', RIGHTS['CAP_GETSOCKOPT'])
CAP_IOCTL = Right('CAP_IOCTL', RIGHTS['CAP_IOCTL'])
CAP_KQUEUE = Right('CAP_KQUEUE', RIGHTS['CAP_KQUEUE'])
CAP_KQUEUE_CHANGE = Right('CAP_KQUEUE_CHANGE', RIGHTS['CAP_KQUEUE_CHANGE'])
CAP_KQUEUE_EVENT = Right('CAP_KQUEUE_EVENT', RIGHTS['CAP_KQUEUE_EVENT'])
CAP_LINKAT = Right('CAP_LINKAT', RIGHTS['CAP_LINKAT'])
CAP_LISTEN = Right('CAP_LISTEN', RIGHTS['CAP_LISTEN'])
CAP_LOOKUP = Right('CAP_LOOKUP', RIGHTS['CAP_LOOKUP'])
CAP_MAC_GET = Right('CAP_MAC_GET', RIGHTS['CAP_MAC_GET'])
CAP_MAC_SET = Right('CAP_MAC_SET', RIGHTS['CAP_MAC_SET'])
CAP_MKDIRAT = Right('CAP_MKDIRAT', RIGHTS['CAP_MKDIRAT'])
CAP_MKFIFOAT = Right('CAP_MKFIFOAT', RIGHTS['CAP_MKFIFOAT'])
CAP_MKNODAT = Right('CAP_MKNODAT', RIGHTS['CAP_MKNODAT'])
CAP_MMAP = Right('CAP_MMAP', RIGHTS['CAP_MMAP'])
CAP_MMAP_R = Right('CAP_MMAP_R', RIGHTS['CAP_MMAP_R'])
CAP_MMAP_RW = Right('CAP_MMAP_RW', RIGHTS['CAP_MMAP_RW'])
CAP_MMAP_RWX = Right('CAP_MMAP_RWX', RIGHTS['CAP_MMAP_RWX'])
CAP_MMAP_RX = Right('CAP_MMAP_RX', RIGHTS['CAP_MMAP_RX'])
CAP_MMAP_W = Right('CAP_MMAP_W', RIGHTS['CAP_MMAP_W'])
CAP_MMAP_WX = Right('CAP_MMAP_WX', RIGHTS['CAP_MMAP_WX'])
CAP_MMAP_X = Right('CAP_MMAP_X', RIGHTS['CAP_MMAP_X'])
CAP_PDGETPID = Right('CAP_PDGETPID', RIGHTS['CAP_PDGETPID'])
CAP_PDKILL = Right('CAP_PDKILL', RIGHTS['CAP_PDKILL'])
CAP_PDWAIT = Right('CAP_PDWAIT', RIGHTS['CAP_PDWAIT'])
CAP_PEELOFF = Right('CAP_PEELOFF', RIGHTS['CAP_PEELOFF'])
CAP_PREAD = Right('CAP_PREAD', RIGHTS['CAP_PREAD'])
CAP_PWRITE = Right('CAP_PWRITE', RIGHTS['CAP_PWRITE'])
CAP_READ = Right('CAP_READ', RIGHTS['CAP_READ'])
CAP_RECV = Right('CAP_RECV', RIGHTS['CAP_RECV'])
CAP_RENAMEAT = Right('CAP_RENAMEAT', RIGHTS['CAP_RENAMEAT'])
CAP_SEEK = Right('CAP_SEEK', RIGHTS['CAP_SEEK'])
CAP_SEM_GETVALUE = Right('CAP_SEM_GETVALUE', RIGHTS['CAP_SEM_GETVALUE'])
CAP_SEM_POST = Right('CAP_SEM_POST', RIGHTS['CAP_SEM_POST'])
CAP_SEM_WAIT = Right('CAP_SEM_WAIT', RIGHTS['CAP_SEM_WAIT'])
CAP_SEND = Right('CAP_SEND', RIGHTS['CAP_SEND'])
CAP_SETSOCKOPT = Right('CAP_SETSOCKOPT', RIGHTS['CAP_SETSOCKOPT'])
CAP_SHUTDOWN = Right('CAP_SHUTDOWN', RIGHTS['CAP_SHUTDOWN'])
CAP_SYMLINKAT = Right('CAP_SYMLINKAT', RIGHTS['CAP_SYMLINKAT'])
CAP_TTYHOOK = Right('CAP_TTYHOOK', RIGHTS['CAP_TTYHOOK'])
CAP_UNLINKAT = Right('CAP_UNLINKAT', RIGHTS['CAP_UNLINKAT'])
CAP_WRITE = Right('CAP_WRITE', RIGHTS['CAP_WRITE'])


class CapabilitiesError(Exception):

    def __init__(self, message, errno=None):
        super(CapabilitiesError, self).__init__(message)
        self.errno = errno


class Rights(object):
    _rights = None

    def __init__(self, *rights):
        bad = set(rights) - Right.ALL
        if bad:
            raise CapabilitiesError('Invalid rights: {}'.format(tuple(bad)))
